import Link from "next/link";
import { INSTALL_COMMAND, PACKAGE_NAME } from "../lib/package";
import { AppearanceToggle } from "../components/appearance-toggle";
import { Brand } from "../components/brand";
import { DocsToc } from "../components/docs-toc";

function Code({ children }: { children: string }) { return <pre className="code-block"><code>{children}</code></pre>; }

const sections = ["install", "data", "charts", "themes", "reference", "behavior", "accessibility", "help"];

export default function DocsPage() {
  return <main><nav className="site-nav docs-nav shell"><Brand /><div className="nav-links"><Link href="/">Gallery</Link><a href="#reference">API</a></div><div className="nav-actions"><AppearanceToggle /><Link className="nav-install nav-docs-mobile" href="/">Charts <span>↗</span></Link></div></nav>
    <div className="docs-layout shell"><DocsToc sections={sections} /><article className="docs-content">
      <section id="install"><p className="eyebrow">01 · Start here</p><h2>Install Generative Charts</h2><Code>{INSTALL_COMMAND}</Code><p>Import the stylesheet once near your application root, then import chart components directly from the package.</p><Code>{`import { LineChart } from "${PACKAGE_NAME}";\nimport "${PACKAGE_NAME}/styles.css";\n\nconst data = [\n  { month: "Jan", revenue: 42 },\n  { month: "Feb", revenue: 58 },\n  { month: "Mar", revenue: 51 },\n];\n\n<LineChart\n  data={data}\n  xKey="month"\n  series={[{ dataKey: "revenue", label: "Revenue" }]}\n  theme="mono-editorial"\n  appearance="light"\n  title="Monthly revenue"\n/>`}</Code><div className="docs-callout"><strong>Coming to npm</strong><p><code>{PACKAGE_NAME}</code> is being prepared for its first public release.</p></div></section>
      <section id="data"><p className="eyebrow">02 · Data contracts</p><h2>Objects in, chart out.</h2><p>Cartesian charts accept an array of ordinary objects, one key for the horizontal category or value, and a typed series array. Pie charts use name and value keys. Heatmaps and terrain use three keyed dimensions.</p><Code>{`type Series<T> = {\n  dataKey: keyof T;\n  label: string;\n  color?: string;\n};`}</Code><p>Numeric strings are accepted. Missing and non-finite values are ignored safely. If no usable values remain, the component renders an accessible empty state.</p></section>
      <section id="charts"><p className="eyebrow">03 · Components</p><h2>Eighteen useful families.</h2><div className="docs-card-grid">{[
        ["BarChart","Vertical, horizontal, grouped, stacked, and diverging category comparisons."],["LineChart","Single and multi-series trends with smooth or linear paths."],["AreaChart","Single, multiple, and stacked area treatments."],["ScatterChart","Single or multi-series relationships with optional point sizing."],["PieChart","Pie and donut composition with optional center content."],["RadarChart","Single or comparison profiles across three or more dimensions."],["HeatmapChart","Categorical matrices with a continuous intensity scale."],["TerrainChart","Projected 3D surfaces with wireframe, point cloud, and peak annotations."],
        ["CohortChart","Retention matrices with cohort sizes, pending periods, and exact values."],["RadialChart","Progress rings, full gauges, and compact half gauges."],["FunnelChart","Tapered conversion funnels and comparable stage bars."],["SankeyChart","Weighted flows through multi-stage journeys."],["TreemapChart","Space-filling composition for many contributors."],["WaterfallChart","Positive and negative contributions between totals."],["ComboChart","Bars and lines sharing one categorical plot."],["HistogramChart","Frequency distributions across numeric bins."],["BoxPlotChart","Quartiles, medians, ranges, and grouped distributions."],["ChoroplethChart","GeoJSON-style regional intensity maps."],
      ].map(([name,copy]) => <div className="docs-card" key={name}><strong>{name}</strong><p>{copy}</p></div>)}</div><h3>Cohort retention</h3><Code>{`<CohortChart\n  data={retention}\n  cohortKey="cohort"\n  periodKey="period"\n  valueKey="retained"\n  sizeKey="users"\n/>`}</Code><h3>Bar variations</h3><Code>{`<BarChart variant="horizontal" layout="grouped" ... />\n<BarChart variant="vertical" layout="stacked" ... />\n\n// Signed values automatically diverge from zero.\n<BarChart data={[{ label: "Growth", change: 24 }, { label: "Churn", change: -11 }]} categoryKey="label" series={[{ dataKey: "change", label: "MRR change" }]} />`}</Code><h3>Line and area variations</h3><Code>{`<LineChart curve="linear" showPoints={false} ... />\n<AreaChart curve="smooth" stacked ... />`}</Code><h3>Pie and donut</h3><Code>{`<PieChart variant="donut" centerLabel="100%" ... />\n<PieChart variant="extruded" ... />`}</Code><h3>3D terrain</h3><Code>{`<TerrainChart data={data} xKey="x" zKey="z" valueKey="elevation" density="medium" />`}</Code></section>
      <section id="themes"><p className="eyebrow">04 · Themes</p><h2>Three themes. Two modes.</h2><p>Generative Charts ships Mono Editorial, Neon Instruments, and Airform. The universal <code>appearance</code> prop switches any theme between light and dark without changing its visual identity.</p><Code>{`import { createTheme } from "${PACKAGE_NAME}";\n\n<LineChart theme="neon-instruments" appearance="dark" ... />\n\nconst brandTheme = createTheme("mono-editorial", {\n  id: "acme",\n  name: "Acme",\n  light: { palette: ["#5b5bd6", "#29a37a"] },\n  dark: { palette: ["#a5b4fc", "#6ee7b7"] },\n});`}</Code><p>Theme variables are scoped to each chart figure. Generative Charts never changes global colors or typography.</p></section>
      <section id="reference"><p className="eyebrow">05 · Reference</p><h2>Shared props</h2><div className="prop-table">{[
        ["data","TDatum[]","Rows rendered by the chart."],["theme","ThemeId | ChartTheme","One of three theme families or a custom theme."],["appearance","light | dark","Universal appearance; defaults to light."],["height","number","Responsive chart height; defaults to 380."],["animate","boolean","Subtle entry animation; defaults to true."],["showLegend","boolean","Show series controls when multiple series exist."],["showTooltip","boolean","Enable pointer and keyboard tooltips."],["valueFormatter","(value) => string","Format axes and interactive values."],["getDatumLabel","function","Override the accessible mark label."],["onDatumClick","function","Handle pointer or keyboard activation."],["title / description / source","string","Semantic chart context and visible framing."],
      ].map(([prop,type,copy]) => <div className="prop-row" key={prop}><code>{prop}</code><span>{type}</span><span>{copy}</span></div>)}</div></section>
      <section id="behavior"><p className="eyebrow">06 · Behavior</p><h2>Responsive and server-safe.</h2><p>Charts measure the available container width and reflow their SVG geometry to keep labels readable. Height remains explicit, with compact layouts for narrow containers. IDs come from React’s stable <code>useId</code> API.</p><h3>Legends</h3><p>When more than one series is present, legend controls can hide and restore individual series. Domains and geometry update from the remaining visible series.</p><h3>Animation</h3><p>Marks enter with a short stagger. Set <code>animate={`{false}`}</code> to disable it. The stylesheet automatically removes transitions for reduced-motion users.</p></section>
      <section id="accessibility"><p className="eyebrow">07 · Accessibility</p><h2>Readable in more than one way.</h2><ul><li>Every SVG receives a programmatic title and description.</li><li>Every interactive mark is keyboard focusable and activates with Enter or Space.</li><li>The same tooltip shown on hover appears on keyboard focus.</li><li>Legends use pressed-state buttons instead of color-only controls.</li><li>Semantic chart text never drops below 12px.</li><li>Empty datasets produce a visible and announced status.</li></ul></section>
      <section id="help"><p className="eyebrow">08 · Help</p><h2>Troubleshooting</h2><h3>The chart has no styles</h3><p>Import <code>{PACKAGE_NAME}/styles.css</code> once in your root layout or application entry point.</p><h3>The chart shows an empty state</h3><p>Confirm that your series keys exist and contain at least one finite numeric value.</p><h3>The chart is too short</h3><p>Pass a larger <code>height</code>. Width always follows the containing element.</p><div className="docs-callout"><strong>Still stuck?</strong><p>Open an issue with a small data sample, the component props, and the React version in use.</p></div></section>
    </article></div>
  </main>;
}
